= Coordinate transactions and enforce causal consistency

When working with a cluster, _bookmarks_ allow you to chain transactions and enforce <<causal_consistency>>.
A bookmark is a token that represents some state of the database.
By passing one or multiple bookmarks along with a query, the server will make sure that the query does not get executed before the represented state(s) have been established.

On requests that _commit_ a transaction (i.e. to the `tx/commit` endpoint), the response includes a `lastBookmarks` key containing an array of encoded bookmarks, which represent the state of the transaction's committed changes.

====
[discrete]
=== Example request

[source, headers]
----
POST http://localhost:7474/db/neo4j/tx/commit
Accept: application/json;charset=UTF-8
Content-Type: application/json
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
----

[source, JSON]
----
{
  "statements": [
    {
      "statement": "MERGE (p1:Person {name: $name}) MERGE (p2:Person {name: $otherName}) RETURN p1.name, p2.name",
      "parameters": {
        "name": "Alice",
        "otherName": "Bob"
      }
    }
  ]
}
----

[discrete]
=== Example response

[source, headers]
----
200: OK
Content-Type: application/json;charset=utf-8
----

[source, JSON]
----
{
  "results": [ {
    "columns": [ "p1.name", "p2.name" ],
    "data": [ {
      "row": [ "Alice", "Bob" ],
      "meta": [ null, null ]
    } ]
  } ],
  "errors": [],
  "lastBookmarks": [
    "FB:kcwQt8DpQx5zR0uN3Oj/OudM3QaQ"
  ]
}
----
====

You can use the bookmarks returned in the response in a subsequent transaction's `Bookmarks` header, if you want to causally chain those transactions together.
This header should contain an array of bookmark strings.
The server waits until it has caught up with the changes encapsulated in the bookmarks before executing the submitted transaction.

In the example below, the server does not execute the transaction until it has registered the changes associated with the bookmarks `FB:kcwQt8DpQx5zR0uN3Oj/OudM3QaQ` and `FB:kcwQy9mp3ioyRom386bZDRRcuCiQ`.

====
[discrete]
=== Example request

[source, headers]
----
POST http://localhost:7474/db/neo4j/tx/commit
Accept: application/json;charset=UTF-8
Content-Type: application/json
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
Bookmarks: ["FB:kcwQt8DpQx5zR0uN3Oj/OudM3QaQ", "FB:kcwQy9mp3ioyRom386bZDRRcuCiQ"]
----

[source, JSON]
----
{
  "statements": [
    {
      "statement": "MATCH (p1:Person {name: $source}) MATCH (p2:Person {name: $end}) MERGE (p1)-[:LIKES]->(p2)",
      "parameters": {
        "source": "Alice",
        "end": "Bob"
      }
    }
  ]
}
----
====

[NOTE]
====
Bookmarks returned by the server are not intended to be parsed or modified by the client and should simply be inserted as is into the `Bookmarks` header.
====


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{partials}/glossary.adoc[]
endif::[]
