= Headers

This page contains a full list of headers you may use to tweak the HTTP API behavior, or that the API may return in responses.

== Request headers

[cols="1m, 3"]
|===
|Header |Description

|Accept
|label:deprecated[Not deprecated] Desired format of the response body. +
Possible values are `application/json` (default), `application/vnd.neo4j.jolt-v2`, or `application/vnd.neo4j.jolt-v2+json-seq`.footnote:[The `application/json` format is not deprecated, but the JOLT formats are deprecated.] +
For more information, see xref:result-formats.adoc[].

|Access-Mode
|Whether the query should be routed to cluster readers or writers. +
Possible values are `READ` or `WRITE` (default). +
For more information, see xref:routing.adoc[].

|Authorization
|label:deprecated[Not deprecated] Authentication credentials to authorize the request. +
For more information, see xref:authentication-authorization.adoc[].

|Bookmarks
|A list of bookmarks the server should wait for before executing the current request. +
For more information, see xref:bookmarks.adoc[].

|Content-Type
|label:deprecated[Not deprecated] The format of the request body. +
The only possible value is `application/json`.

|===

== Response headers

[cols="1m, 3"]
|===
|Header |Description

|Content-Type
|The format of the response body (matches the `Accept` request header). +
Possible values are `application/json` (not deprecated), `application/vnd.neo4j.jolt-v2`, or `application/vnd.neo4j.jolt-v2+json-seq`.footnote:[The `application/json` format is not deprecated, but the JOLT formats are deprecated.]
For more information, see xref:result-formats.adoc[].

|===
