:description: The Neo4j HTTP API allows to execute a series of Cypher statements against a Neo4j server through HTTP requests.

= Introduction

[WARNING]
====
The HTTP API is currently not available on link:{neo4j-docs-base-uri}/aura[Neo4j Aura].
====

The Neo4j HTTP API allows to execute a series of Cypher statements against a Neo4j server through HTTP requests.

The main use case of the HTTP API is for developing client applications in languages for which there is no supported library.
If there exists an official library (driver) for the language you are using, consider using that instead -- see link:{neo4j-docs-base-uri}/create-applications/[Create applications].

This guide assumes that you have:

- a running Neo4j instance -- if not, check out how to link:{neo4j-docs-base-uri}/operations-manual/current/installation/[install Neo4j]
- some familiarity with <<Cypher>> -- if you need a hand, check out link:{neo4j-docs-base-uri}/getting-started/cypher-intro/[Getting started -> Cypher].

To execute queries through the HTTP API, you may use either:

- xref:query.adoc[Implicit transactions] -- you just submit queries, the API takes care of the transaction handling for you
- xref:transactions.adoc[Explicit transactions] -- you control the lifecycle of the transaction (open, commit, rollback), within which you can execute queries.

[TIP]
By default, the HTTP API uses port 7474 for HTTP and port 7473 for HTTPS.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{partials}/glossary.adoc[]
endif::[]
