= Query the database

To run a query on a database, submit a `POST` request to the following endpoint:

----
http://<host>:<port>/db/<databaseName>/tx/commit
----

- `<host>` is where the Neo4j instance is located (example `localhost`, `xxx.databases.neo4j.io`),
- `<port>` is the port on which the Neo4j HTTP server is set to listen on (default `7474`),
- `<databaseName>` is the database you want to query (example `neo4j`).

The server wraps the submitted Cypher query in a (implicit) transaction for you.
This means that in case any part of the query fails, the database will be reverted back to its status before any part of the query was executed.
To control the lifecycle of transactions, see xref:transactions.adoc[Run transactions].

[TIP]
--
Each request must include an `Authorization` header, see xref:authentication-authorization.adoc[Authentication and authorization] for more information.
--

====
[discrete]
=== Example request

[source, headers]
----
POST http://localhost:7474/db/neo4j/tx/commit
Accept: application/json;charset=UTF-8
Content-Type: application/json
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
----

[source, JSON]
----
{
  "statements": [
    {
      "statement": "MERGE (n:Person {name: $name, age: $age}) RETURN n",
      "parameters": {
        "name": "Alice",
        "age": 42
      }
    }
  ]
}
----

[discrete]
=== Example response

[source, headers]
----
200: OK
Content-Type: application/json;charset=utf-8
----

[source, JSON, role=nocollapse]
----
{
  "results": [ {
    "columns": ["n"],
    "data": [ {
      "row": [ {
        "name": "Alice",
        "age": 42
      } ],
      "meta": [ {
        "id": 36,
        "elementId": "4:0ea4a108-32c5-498c-99e7-95cc67ab5f7d:36",
        "type": "node",
        "deleted": false
      } ]
    } ]
  } ],
  "errors": [],
  "lastBookmarks": [
    "FB:kcwQDqShCDLFSYyZ55XMZ6tffRuQ"
  ]
}
----
====

[TIP]
====
**Literal line breaks are not allowed inside Cypher statements** submitted through the API (as per JSON specifications).
This means that queries should fit on a single line.
You can replace line breaks with spaces, as Cypher parses them equivalently.
====

== Execute multiple queries

You can send multiple Cypher statements in the same request.
The server runs them in sequence, but separate from each other, so a statement cannot reference a variable defined in another statement.
The response contains the result of each statement, in order.

====
[discrete]
=== Example request

[source, headers]
----
POST http://localhost:7474/db/neo4j/tx/commit
Accept: application/json;charset=UTF-8
Content-Type: application/json
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
----

[source, JSON]
----
{
  "statements": [
    { "statement": "RETURN 1" },
    { "statement": "RETURN 2" }
  ]
}
----

[discrete]
=== Example response

[source, headers]
----
200: OK
Content-Type: application/json;charset=utf-8
----

[source, JSON]
----
{
  "results": [
    {
      "columns": ["1"],
      "data": [{ "row": [1], "meta": [null] }]
    },
    {
      "columns": ["2"],
      "data": [{ "row": [2], "meta": [null] }]
    }
  ],
  "errors": [],
  "lastBookmarks": [
    "FB:kcwQDqShCDLFSYyZ55XMZ6tffRuQ"
  ]
}
----
====

**If one of the queries fails, _all statements_ submitted with the request will be rolled back.**
In the example below, the second statement fails due to a division by 0.
The result is that not only no `:Number` nodes are created (not even the one with `val: 1`), but no `:Person` nodes are created either.

====
[discrete]
=== Example request

[source, headers]
----
POST http://localhost:7474/db/neo4j/tx/commit
Accept: application/json;charset=UTF-8
Content-Type: application/json
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
----

[source, JSON]
----
{
  "statements": [
    {
      "statement": "MERGE (p:Person {name: $name}) RETURN p",
      "parameters": {
        "name": "Bob"
      }
    },
    {
      "statement": "UNWIND [1, 0] AS i MERGE (n:Number {val: 1/i}) RETURN n"
    },
  ]
}
----

[discrete]
=== Example response

[source, headers]
----
200: OK
Content-Type: application/json;charset=utf-8
----

[source, JSON]
----
{
  "results": [ {
    "columns": [ "p" ],
    "data": [ {
      "row": [ {
        "name": "Bob"
      } ],
      "meta": [ {
        "id": 8,
        "elementId": "4:0ea4a108-32c5-498c-99e7-95cc67ab5f7d:8",
        "type": "node",
        "deleted": false
      } ]
    ] }
  ] },
  {
    "columns": [ "n" ],
    "data": [ {
      "row": [ {
        "val": 1
      } ],
      "meta": [ {
        "id": 1,
        "elementId": "4:0ea4a108-32c5-498c-99e7-95cc67ab5f7d:1",
        "type": "node",
        "deleted": false
      } ]
    } ]
  } ],
  "errors": [ {
    "code": "Neo.ClientError.Statement.ArithmeticError",
    "message": "/ by zero"
  } ]
}
----
====


== Queries with `CALL {} IN TRANSACTIONS`

Take extra care with queries using the Cypher clause link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/call-subquery/#subquery-call-in-transactions[`CALL {} IN TRANSACTIONS`].
Because those queries spawn further transactions of their own, there can be unexpected behaviors due to their interaction with the surrounding transaction.


=== Rollback behaviour

While a failure in _any_ statement will cause _all_ statements in the request to be rolled back, **that does not apply to the ones using `CALL {} IN TRANSACTIONS`**.
Since the transactions created by that clause get independently committed, the server cannot roll them back in case the other parts fail.

In the example below, even if the second statement fails execution due to the division by zero, the first statement is not reverted.
The result is two new `:Person` nodes.

====
[source, headers]
----
POST http://localhost:7474/db/neo4j/tx/commit
Accept: application/json;charset=UTF-8
Content-Type: application/json
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
----

[source, JSON]
----
{
  "statements": [
    {
      "statement": "UNWIND ['Sofia', 'Greg'] AS name CALL { WITH name CREATE (:Person {name: name}) } IN TRANSACTIONS OF 1 ROWS RETURN name"
    },
    {
      "statement": "UNWIND [1, 0] AS i MERGE (n:Number {val: 1/i}) RETURN n"
    },
  ]
}
----
====


=== Query order

Queries containing `CALL {} In TRANSACTIONS` must come first in the order of the `statements` JSON list.
Failure to do so will result in an error.

====
[discrete]
=== Example request

[source, headers]
----
POST http://localhost:7474/db/neo4j/tx/commit
Accept: application/json;charset=UTF-8
Content-Type: application/json
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
----

[source, JSON]
----
{
  "statements": [
    {
      "statement": "MERGE (p:Person {name: $name}) RETURN p.name",
      "parameters": {
        "name": "Bob"
      }
    },
    {
      "statement": "UNWIND [1, 0] AS i CALL { WITH i MERGE (:Number {val: 1/i}) } IN TRANSACTIONS OF 1 ROWS RETURN i"
    },
  ]
}
----

[discrete]
=== Example response

[source, headers]
----
200: OK
Content-Type: application/json;charset=utf-8
----

[source, JSON, role=nocollapse]
----
{
  "results": [ {
    "columns": [ "p.name" ],
    "data": [ {
      "row": [ "Bob" ],
      "meta": [ null ]
    }]
  },
  {
    "columns": [ "i" ],
    "data": []
  } ],
  "errors": [ {
    "code": "Neo.DatabaseError.Statement.ExecutionFailed",
    "message": "Expected transaction state to be empty when calling transactional subquery. (Transactions committed: 0)"
  } ]
}
----
====


== Query parameters

In order to speed up queries in repeated scenarios, avoid using literals and replace them with parameters wherever possible.
This allows the server to cache query plans and can result in a significant performance improvement.

.Do -- Use query parameters
[source, JSON]
----
{
  "statements": [
    {
      "statement": "MERGE (n:Person {name: $name, age: $age}) RETURN n",
      "parameters": {
        "name": "Alice",
        "age": 42
      }
    }
  ]
}
----

.Do not -- Embed literals in query
[source, JSON]
----
{
  "statements": [
    {
      "statement": "MERGE (n:Person {name: 'Alice', age: 42}) RETURN n",
    }
  ]
}
----

See link:{neo4j-docs-base-uri}/cypher-manual/current/syntax/parameters/[Cypher Manual -> Parameters] for more information.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{partials}/glossary.adoc[]
endif::[]
