:description: This section describes the authentication and authorization required to use the HTTP API.

[[http-api-security]]
= Authentication and authorization

Authentication and authorization are enabled by default in Neo4j (refer to xref:4.1@operations-manual:ROOT:authentication-authorization/index.adoc#auth[Operations Manual -> Authentication and authorization]).
With authentication and authorization enabled, requests to the HTTP API must be authorized using the username and password of a valid user.


[[http-api-missing-authorization]]
== Missing authorization

If an `Authorization` header is not supplied, the server will reply with an error.

_Example request_

* *+POST+*  +http://localhost:7474/db/neo4j/tx/commit+
* *+Accept:+* +application/json;charset=UTF-8+
* *+Content-Type:+* +application/json+

[source, JSON, role="nocopy"]
----
{
  "statements": [
    {
      "statement": "CREATE (n:MyLabel) RETURN n"
    }
  ]
}
----

_Example response_

* *+401:+* +Unauthorized+
* *+Content-Type:+* +application/json;charset=utf-8+
* *+WWW-Authenticate:+* +Basic realm="Neo4j"+

[source, JSON, role="nocopy"]
----
{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.Unauthorized",
    "message" : "No authentication header supplied."
  } ]
}
----

[NOTE]
====
If authentication and authorization have been disabled, HTTP API requests can be sent without an `Authorization` header.
====


[[http-api-incorrect-authentication]]
== Incorrect authentication

If an incorrect username or password is provided, the server replies with an error.

_Example request_

* *+POST+*  +http://localhost:7474/db/neo4j/tx/commit+
* *+Accept:+* +application/json;charset=UTF-8+
* *+Authorization:+* +Basic bmVvNGo6aW5jb3JyZWN0+
* *+Content-Type:+* +application/json+

[source, JSON, role="nocopy"]
----
{
  "statements": [
    {
      "statement": "CREATE (n:MyLabel) RETURN n"
    }
  ]
}
----

_Example response_

* *+401:+* +Unauthorized+
* *+Content-Type:+* +application/json;charset=utf-8+
* *+WWW-Authenticate:+* +Basic realm="Neo4j"+

[source, JSON, role="nocopy"]
----
{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.Unauthorized",
    "message" : "Invalid username or password."
  } ]
}
----

