:description: This section describes the authentication and authorization required to use the HTTP API.

[[http-api-security]]
= Authentication and authorization

Authentication and authorization are enabled by default in Neo4j (refer to link:{neo4j-docs-base-uri}/operations-manual/{page-version}/authentication-authorization#auth[Operations Manual -> Authentication and authorization]).
With authentication and authorization enabled, requests to the HTTP API must be authorized using the username and password of a valid user.

[NOTE]
====
If authentication and authorization have been disabled, HTTP API requests can be sent without an `Authorization` header.
====


[[http-api-successful-authorization]]
== Authorizing a Request

Each HTTP request requires a `Authorization` header. The header value encoding follows standard format for `Basic` authentication (RFC 7617) and therefore must be in the following format:

----
Authorization: Basic <base64 encoding of username:credential>
----

For example, if we wish to authenticate as user `neo4j` with credential `verysecret` we combine them with `:` so that we have:
----
neo4j:verysecret
----
Then we base64 encode that value to:
----
bmVvNGo6dmVyeXNlY3JldA==
----

.How to base64 encode a string
[%collapsible]
====
To base64 encode a string on a Linux or Mac machine, use the built-in `base64` command:

[source, bash]
----
echo -n "neo4j:verysecret" | base64
----
====

Finally we append `Basic` to the beginning to have the following as the final header:

----
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
----

[discrete]
=== Complete Request Example

* *+POST+*  +http://localhost:7474/db/neo4j/tx/commit+
* *+Accept:+* +application/json;charset=UTF-8+
* *+Content-Type:+* +application/json+
* *+Authorization:+* +Basic bmVvNGo6dmVyeXNlY3JldA==+

[source, JSON, role="nocopy"]
----
{
  "statements": [
    {
      "statement": "RETURN 1"
    }
  ]
}
----

_Example response_

* *+200:+* +OK+
* *+Content-Type:+* +application/json;charset=utf-8+

[source, JSON, role="nocopy"]
----
{
    "results": [ {
      "columns": ["1"],
      "data": [{"row": [1], "meta": [null]}] }],
    "errors": []
}
----

[[http-api-missing-authorization]]
== Missing authorization

If an `Authorization` header is not supplied, the server will reply with an error.

_Example request_

* *+POST+*  +http://localhost:7474/db/neo4j/tx/commit+
* *+Accept:+* +application/json;charset=UTF-8+
* *+Content-Type:+* +application/json+

[source, JSON, role="nocopy"]
----
{
  "statements": [
    {
      "statement": "CREATE (n:MyLabel) RETURN n"
    }
  ]
}
----

_Example response_

* *+401:+* +Unauthorized+
* *+Content-Type:+* +application/json;charset=utf-8+
* *+WWW-Authenticate:+* +Basic realm="Neo4j"+

[source, JSON, role="nocopy"]
----
{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.Unauthorized",
    "message" : "No authentication header supplied."
  } ]
}
----

[NOTE]
====
If authentication and authorization have been disabled, HTTP API requests can be sent without an `Authorization` header.
====


[[http-api-incorrect-authentication]]
== Incorrect authentication

If an incorrect username or password is provided, the server replies with an error.

_Example request_

* *+POST+*  +http://localhost:7474/db/neo4j/tx/commit+
* *+Accept:+* +application/json;charset=UTF-8+
* *+Authorization:+* +Basic bmVvNGo6aW5jb3JyZWN0+
* *+Content-Type:+* +application/json+

[source, JSON, role="nocopy"]
----
{
  "statements": [
    {
      "statement": "CREATE (n:MyLabel) RETURN n"
    }
  ]
}
----

_Example response_

* *+401:+* +Unauthorized+
* *+Content-Type:+* +application/json;charset=utf-8+
* *+WWW-Authenticate:+* +Basic realm="Neo4j"+

[source, JSON, role="nocopy"]
----
{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.Unauthorized",
    "message" : "Invalid username or password."
  } ]
}
----


[[http-api-auth-failure-rollback]]
== Authentication failure on open transactions

A `Neo.ClientError.Security.Unauthorized` error will typically imply a transaction rollback.
However, due to the way authentication is processed in the HTTP server, the transaction will remain open.

