:description: HTTP API routing.

[[http-api-actions-cluster-routing]]
= Clusters and routing

The Cypher Transactional API provides a limited level of support for query routing.

The level of support depends on whether link:https://neo4j.com/docs/operations-manual/current/clustering/internals/#clustering-routing[Server-side routing] has been enabled:

[options="header", cols="20m,80a"]
|===
| Server-side routing
| Support

|disabled
|Clusters support read-only queries.

|enabled
|Clusters support routing for queries that involve a xref::/actions/begin-and-commit-a-transaction-in-one-request.adoc[single request] (i.e. via the `tx/commit` endpoint).
This is because the cluster does not currently support transaction identifiers across the cluster.

By default, all transactions are considered `WRITE` transactions, even if they contain no Cypher with write operations. This can be overridden by setting a value of `READ` in the `access-mode` header of the request (see xref::/actions/transaction-configuration.adoc[Transaction Configuration - Access Mode]).

This default has the effect that all queries are ultimately executed on the leader. To ensure efficient load balancing of `READ` transactions, you must label them as such in the request.
|===