:description: Configuring HTTP Transactions.

[[http-api-actions-transaction-configuration]]
= Transaction Configuration

For any transaction-initiating request (such as `/tx` or `tx/commit`), you can provide configuration options that apply for the duration of the whole transaction.


[[http-api-actions-access-mode]]
== Access Mode

To ensure efficient load balancing across a cluster, it is important to label transactions that only contain `READ` statements with a `READ` access mode.

This can be done by adding an `access-mode` header to the request, with a value of `READ`.


[WARNING]
====
If an `access-mode` configuration has *not* been provided, the default value is `WRITE`.

However, if you have clusters with link:https://neo4j.com/docs/operations-manual/current/clustering/internals/#causal-clustering-routing[Server-side routing] disabled, the default value is `READ`.
====

[NOTE]
====
Please note that `access-mode` is not required for a Neo4j single instance.
====

_Example request_

* *+POST+* +http://localhost:7474/db/neo4j/tx/commit+
* *+Accept:+* +application/json;charset=UTF-8+
* *+Content-Type:+* +application/json+
* *+Access-Mode:+*  +WRITE+

[source, JSON, role="nocopy"]
----
{
  "statements": [
    {
      "statement": "CREATE (n) RETURN n"
    }
  ]
}
----

_Example response_

* *+200:+* +OK+
* *+Content-Type:+* +application/json;charset=utf-8+

[source, JSON, role="nocopy"]
----
{
  "results" : [ {
    "columns" : [ "n" ],
    "data" : [ {
      "row" : [ { } ],
      "meta" : [ {
        "id" : 7,
        "type" : "node",
        "deleted" : false
      } ]
    } ]
  } ],
  "errors" : [ ]
}
----

[[http-api-actions-bookmarks-mode]]
== Bookmarks

When working with a Causal Cluster, transactions can be chained, via a bookmarks, to ensure causal consistency. See xxx for more about how this works.

`Bookmarks` can be added to the header of a transaction initiating request. This header contains an array of strings with the encoded bookmark. The server will ensure the transaction being executed is up to date with each of the bookmarks supplied before executing the query. For example:


_Example request_

* *+POST+* +http://localhost:7474/db/neo4j/tx/commit+
* *+Accept:+* +application/json;charset=UTF-8+
* *+Content-Type:+* +application/json+
* *+Bookmarks:+*  +["FB:kcwQy9mp3ioyRom386bZDRRcuCeQ", "FB:kcwQy9mp3ioyRom386bZDRRcuCiQ"]+

[source, JSON, role="nocopy"]
----
{
  "statements": [
    {
      "statement": "RETURN 1 as n"
    }
  ]
}
----

On requests that commit a transaction the response will contain a `lastBookmarks` property containing array of encoded bookmarks which represent the state of the transaction's committed changes.

_Example response_

* *+200:+* +OK+
* *+Content-Type:+* +application/json;charset=utf-8+

[source, JSON, role="nocopy"]
----
{
  "results" : [ {
    "columns" : [ "n" ],
    "data" : [ {
      "row" : [ 1 ],
      "meta" : [ null ]
    } ]
  } ],
  "errors" : [ ],
  "lastBookmarks":  ["FB:kcwQy9mp3ioyRom386bZDRRcuCSQ"]
}
----

The bookmarks returned in the response should be used in a subsequent transaction's `Bookmarks` header should you wish the transaction to be causally chained.

[NOTE]
====
Bookmarks returned by the server are not intended to be parsed or modified by the client and should simply be inserted as is into the `Bookmarks` header.
====

